### ISSUE TITLE
Perform experimental evaluation for the paper

### ISSUE THREAD

**Issue by nkarag** [input-output-hk/decentralized-software-updates#101]
- [x] Perform a worst case analysis on the update mechanism impact on the system TBPS.
- [x] Determine whether single node simulation is needed.
- [x] Perform a back of the envelope analysis on the time to activation of an update proposal.
- [x] Write micro-benchmarks to measure the execution time of vote tally.

**Comment by dnadales** [comment]
After discussing this with the other scientists it was decided that no simulations are needed to estimate the impact of the update protocol in the system's throughput (in terms of transaction bytes per-second).

**Comment by dnadales** [comment]
>  Perform a back of the envelope analysis on the time to activation of an update proposal.

This requires that we have a concrete description of the activation phase.

**Comment by dnadales** [comment]
> ￼ Perform a back of the envelope analysis on the time to activation of an update proposal.

This is not needed at the moment. We can't do this with a back of the envelope calculation, as the time to activation depends on other proposals that might be active, and cancel others, or take precedence.

If we need measurements about this we can open a separate issue.
