### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by zimmerle** [input-output-hk/decentralized-software-updates#112]
Hi,

Congrats on what you are doing here. Is there any space for contribution? I would love to participate.

**Comment by dnadales** [comment]
Hi Felipe,

Glad that you're interested in our work. Sure contributions are always welcome! I don't know in which aspects of the project you'd like to contribute: theoretical side or implementation side. In any case, feel free to browse the source code (for the paper and prototype) and get back to us with any questions you might have!

Warm regards,
Damian.

**Comment by dnadales** [comment]
BTW @zimmerle we're also aware that at this stage the documentation might not be newcomers friendly, so feel free to ask any questions you might have! :)

**Comment by zimmerle** [comment]
Hi @dnadales, I am getting familiar with all the content that you guys already have. I am currently a Dr. student working on the same subject, so I have an interest in both: theoretical and implementation.

Had a different approach on the subject described here - https://arxiv.org/abs/1907.12960

**Comment by dnadales** [comment]
Oh, great! @nkarag @mciampi  :point_up: we should read this paper as well :)
