### ISSUE TITLE
Implement a prototype

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/decentralized-software-updates#32]
Implement a prototype for the decentralized software-updates mechanism, so that we can:

- refine the research results
- show its feasibility
- discover potential errors or improvements that were not detected during theoretical research

**Comment by nkarag** [comment]
Also make some initial experimental measurements, if there is a need for that.

**Comment by dnadales** [comment]
Closed in favor of more specific ones:

- https://github.com/input-output-hk/decentralized-software-updates/issues/35
- https://github.com/input-output-hk/decentralized-software-updates/issues/60
- https://github.com/input-output-hk/decentralized-software-updates/issues/61
- https://github.com/input-output-hk/decentralized-software-updates/issues/62
