### ISSUE TITLE
How do we give priority to an urgent UP that must be deployed fast?

### ISSUE THREAD

**Issue by nkarag** [input-output-hk/decentralized-software-updates#5]

**Comment by mciampi** [comment]
It would be nice to have different priority and different thresholds, but maybe this can be abused by the adversary.

**Comment by dionyziz** [comment]
Priority will be given by Delegation. Different thresholds shouldn't be
needed.

**Comment by nkarag** [comment]
See update policies on FC20 submitted paper.
