### ISSUE TITLE
What are the major security assumptions (e.g. honest majority for voters) that we make?

### ISSUE THREAD

**Issue by nkarag** [input-output-hk/decentralized-software-updates#7]

**Comment by mciampi** [comment]
The only assumption that we are going to use is that the majority of the stake belongs to honest parties (which is an implicit assumption in ouroboros). I think that this issue should be closed

**Comment by dionyziz** [comment]
I'm not so certain. What do we assume about bounded stake shift?

**Comment by mciampi** [comment]
Hopefully, we do not need to add additional assumption on the stake shift. But this mostly depend on the voting protocol that we adopt. But of course the stake shifting is a serious concern (I wrote something about it in #8 )
