### ISSUE TITLE
Write down validation criteria for the prototype

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/decentralized-software-updates#77]
This corresponds to Priviledge deliverable D1.2 Validation Criteria (M30, IOResearch). This deliverable will include all the validation criteria that will be applied for each use case.

The validation criteria and methodology could be based on the properties and test we define in #55 #56 #57 and #58.

The deliverable will be developed in the corresponding [priviledge github repo ](https://github.com/guardtime/priviledge-wp1) in the appropriate deliverable folder as a latex file. As deliverable leaders, we should provide an overall document structure for the other teams to fill in. We will fill in only the Cardano use case part.
The deliverable will be developed as a latex file, with different parts separated as distinct .tex files, so as to enable concurrent write up.

**Comment by nkarag** [comment]
**New Deadlines**
15th Sept - 1st draft ready (all uses cases must have contributed) and also have a meeting for alignment
15th Oct - 2nd draft ready (also alignment meeting if required)
30th Nov - Ready for Review
10th Dec - Receive reviewers feedback
20th Dec - Ready for submission

**Comment by dnadales** [comment]
This was already done. See for instance c8cd6e877b8842b27166f8afeebd4eca29e54fe1 in http://github.com:guardtime/priviledge-wp1
