### ISSUE TITLE
Voting system and threshold required to accept a proposal

### ISSUE THREAD

**Issue by mciampi** [input-output-hk/decentralized-software-updates#8]
Currently we are considering two approaches to identify an accepted proposal
1) A proposal has at least the 51% of the preferences (where 51% refers to the active stake)
2) A proposal has at least 90-95% of the preferences.

The proposal 1) has the advantage that an adversary controlling only the minority of the stake cannot stop an update, if the honest parties want update the system according to some proposal. 
The disadvantage of 1) is that the "sentiments" of the parties participating to the blockchain could  change given that the system could be updated even with such a low threshold.

The proposal 2) has the advantage that a proposal is accepted only if almost all the participants are happy about that proposal. The disadvantage is that an adversarial party could always prevent the system to update (which means that critical security fix might not be applied).

In any case, it seems to be that we want to use a voting system that is different from the current one (where the preferences for the proposals are written inside the blocks issued by the miners). In this case we should decide whether to use an approach based on a committee (that is decided in such a way that the majority of the committee is honest), or an approach that allows all the parties to vote.
In both cases we should consider the problem of adaptive/static corruptions of the voters (maybe this is critical only if we use the committee approach).

**Comment by nkarag** [comment]
See FC20 submitted paper.
