### ISSUE TITLE
Write final report on validation criteria testing results.

### ISSUE THREAD

**Issue by nkarag** [input-output-hk/decentralized-software-updates#82]

**Comment by nkarag** [comment]
This corresponds to Priviledge, deliverable D1.3 Use Case Validation (M36, SCCEIV). This document will describe in detail the validation of each use case with respect to the criteria set in D1.2. (T1.3).
It corresponds to the results of tasks

**Comment by dnadales** [comment]
Done. See c8cd6e877b8842b27166f8afeebd4eca29e54fe1 in https://github.com/guardtime/priviledge-wp1
